# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Push Lobby Image

on:
  push:
    branches: [ "prod", "dev" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          --build-arg FORWARDING_SECRET='${{ secrets.FORWARDING_SECRET }}' \
          . -t ghcr.io/${{ github.repository }}/hans-geyser:${{ steps.extract_branch.outputs.branch }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/hans-geyser:${{ steps.extract_branch.outputs.branch }}
